
server:
  port: 9001

spring:
  application:
    name: eureka-server-clustered
  config:
    activate:
      on-profile: "peer-1"

eureka:
  instance:
    hostname: peer-1-server.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer-2-server.com:9002/eureka/,http://peer-3-server.com:9003/eureka/

---

server:
  port: 9002

spring:
  application:
    name: eureka-server-clustered
  config:
    activate:
      on-profile: "peer-2"

eureka:
  instance:
    hostname: peer-2-server.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer-1-server.com:9001/eureka/,http://peer-3-server.com:9003/eureka/

---

server:
  port: 9003

spring:
  application:
    name: eureka-server-clustered
  config:
    activate:
      on-profile: "peer-3"

eureka:
  instance:
    hostname: peer-3-server.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer-1-server.com:9001/eureka/,http://peer-2-server.com:9002/eureka/
