
server:
  port: 0

spring:
  application:
    instance_id: ${random.uuid}
    name: user-service

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer-1-server.com:9001/eureka/,http://peer-2-server.com:9002/eureka/,http://peer-3-server.com:9003/eureka/

management:
  info:
    os:
      enabled: on
    env:
      enabled: on
    java:
      enabled: on
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

